# Copyright (C) 2023 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.
---

version: '3'

includes:
  snippet-placeholder:
    dir: './snippet-placeholder'
    taskfile: './snippet-placeholder'

output: 'prefixed'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'clean'
      - task: 'dependencies'
      - task: 'lint'
    desc: 'Run snippets-related continuous integration tasks'

  clean:
    cmds:
      - 'rm -fr .task node_modules vendor'
    desc: 'Delete snippets-related temporary files and third-party dependencies'

  dependencies:
    cmds:
      - task: 'dependencies:javascript'
      - task: 'dependencies:php'
    desc: 'Install dependencies for linting snippets'

  dependencies:javascript:
    cmds:
      # <http://www.tiernok.com/posts/2019/faster-npm-installs-during-ci/>
      - 'npm ci --prefer-offline --no-audit'
    env:
      CI: true
    desc: 'Install JavaScript dependencies for linting snippets'

  dependencies:php:
    cmds:
      - 'composer install --no-ansi --no-interaction --no-progress'
    desc: 'Install PHP dependencies for linting snippets'

  lint:
    cmds:
      - task: 'lint:javascript'
      - task: 'lint:php'
    desc: 'Run all snippet-linting tasks'

  lint:javascript:
    cmds:
      - 'node_modules/.bin/eslint snippets/*.js'
    desc: 'Lint JavaScript snippets with ESLint'

  lint:php:
    cmds:
      - 'vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff'
    desc: 'Lint PHP snippets with PHP Coding Standards Fixer'
