# Copyright (C) 2023 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.
---

version: '3'

output: 'prefixed'

vars:
  GO_PACKAGES:
    sh: 'go list ./...'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'clean'
      - task: 'lint'
      - task: 'test'
      - task: 'build'
    desc: 'Run continuous integration tasks for "snippet-placeholder"'

  clean:
    cmds:
      - 'rm -fr snippet-placeholder'
    desc: 'Delete the "snippet-placeholder" application'

  build:
    cmds:
      - 'go build .'
    desc: 'Build the "snippet-placeholder" application'

  lint:
    cmds:
      - task: 'lint:golint'
      - task: 'lint:staticcheck'
      - task: 'lint:vet'
    desc: 'Run all linting tasks for "snippet-placeholder"'

  lint:golint:
    cmds:
      - 'golint -set_exit_status {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Golint'

  lint:staticcheck:
    cmds:
      - 'staticcheck {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Staticcheck'

  lint:vet:
    cmds:
      - 'go vet {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Vet'

  test:
    cmds:
      - 'go test {{catLines .GO_PACKAGES}}'
    desc: 'Run all tests'
