# Copyright (C) 2023 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

---
name: 'Lint, Test, and Build Project'

on:
  push:
    branches:
      - 'master'

jobs:
  lint-snippets:
    name: 'Lint snippets'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v3'

      - name: 'Set up Node environment'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18'

      - name: 'Set up PHP environment'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.2'

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'

      - name: 'Ensure all linting-related tasks run successfully'
        run: './bin/task ci'

  lint-test-and-build-snippet-placeholder:
    name: 'Lint, test, and build "snippet-placeholder"'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v3'

      - name: 'Set up Go environment'
        uses: 'actions/setup-go@v3'
        with:
          go-version-file: 'snippet-placeholder/go.mod'

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'

      - name: 'Install Golint and Staticcheck'
        run: |
          go install golang.org/x/lint/golint@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: 'Ensure all linting, testing, and building tasks run successfully'
        run: './bin/task snippet-placeholder:ci'
